kind: ConfigMap
apiVersion: v1
metadata:
  name: snmpd-config
  namespace: openshift-snmp
data:
  snmpd.conf: |2
    com2sec readonly  default         SNMPCOMMUNITY
    group MyROGroup v1         readonly
    group MyROGroup v2c        readonly	
    group MyROGroup usm        readonly
    view all    included  .1                             80
    access MyROGroup ""      any       noauth    exact  all    none   none
    sysname NODENAME
    syslocation SNMPCOMMUNITY
    syscontact SNMPOWNER
    sysdescr NODENAME NODEIP
    rocommunity SNMPCOMMUNITY
    pass_persist .1.3.6.1.2.1.31.1.1.1.18 /usr/bin/ifAlias_persist
  start.sh: |2
    cp /config/snmpd.conf /tmp/
    /bin/sed -i -e "s/NODENAME/${NODENAME}/g" /tmp/snmpd.conf
    /bin/sed -i -e "s/NODEIP/${NODEIP}/g" /tmp/snmpd.conf
    /bin/sed -i -e "s/SNMPCOMMUNITY/${SNMPCOMMUNITY}/g" /tmp/snmpd.conf
    /bin/sed -i -e "s/SNMPOWNER/${SNMPOWNER}/g" /tmp/snmpd.conf
    /usr/local/sbin/snmpd -f -c /tmp/snmpd.conf
