apiVersion: v1
kind: Service
metadata:
  name: snmpd-out
  namespace: openshift-snmp
spec:
  ports:
  - name: 161-udp
    nodePort: 30161
    port: 161
    protocol: UDP
    targetPort: 161
  selector:
    app: snmpd
  type: NodePort
